version: '3.9'

services:

  mysql-db:
    container_name: mysql_db
    image: mysql:9
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=news_db
    ports:
      - "3306:3306"
    volumes:
# Перед запуском отредактировать:
      - /home/anton/Downloads/docker/mysql:/var/lib/mysql

  server-api:
    build:
      context: ./ServerApi
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    depends_on:
      - mysql-db
    restart: always
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/news_db
      - DB_USER=root
      - DB_PASS=admin